ads/urls.py
from django.urls import path
from .views import index, solicitacao, vermais, negociacao, excluir_anuncio, cria_anuncio, meusanuncios, solicitacoesanuncio, aceitar, denuncia
app_name = 'ads'
urlpatterns = [
    path('', index, name="index_url"),
    path('novo/<int:pk>/<int:tipo>', cria_anuncio, name="ad_url"),
    path('excluir/<int:pk>', excluir_anuncio, name="excluir_url"),
    path('vermais/<int:pk>', vermais, name="vermais_url"),
    path('solicitacao/<int:anuncio>/<int:pk>',
         solicitacao, name="solicitacao_url"),
    path('negociacao/<int:pk>', negociacao, name="negociacao_url"),
    path('anuncios/', meusanuncios, name="meus_anuncios"),
    path('solicitacoes/<int:pk>', solicitacoesanuncio,
         name='solicitacoes_anuncio'),
    path('aceitar/<int:ad_pk>/<int:req_pk>', aceitar, name="aceitar"),
    path('denuncia/<int:pk>', denuncia, name="denuncia")
]

bricademy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import home, homemap, sobre
from users import urls as users_urls
from materials import urls as materials_urls
from ads import urls as ads_urls
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('', home, name="home"),
    path('map/', homemap, name="map"),
    path('sobre/', sobre, name="sobre"),
    path('materials/', include(materials_urls)),
    path('users/', include(users_urls)),
    path('ads/', include(ads_urls)),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

materials/urls.py
from django.urls import path
from .views import newMaterial, minhasSolicitacoes, solicitacoesRecebidas, ListMaterials, editMaterial, excluirMaterial

app_name = 'materials'
urlpatterns = [
    path('new', newMaterial, name="new_material"),
    path('list', ListMaterials, name="list_material"),
    path('solicitacoes', minhasSolicitacoes, name="minhas_solicitacoes"),
    path('recebidas', solicitacoesRecebidas, name="solicitacoes_recebidas"),
    path('edit/<int:pk>', editMaterial, name="edit_material"),
    path('excluir/<int:pk>', excluirMaterial, name="excluir_material")
]

materials/models.py
from django.db import models
from django.contrib.auth.models import User


class Subject(models.Model):
    subject = models.CharField('Assunto', max_length=100)
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Modificado em', auto_now=True)

    def __str__(self):
        return self.subject


class Material(models.Model):
    CONSERVATION_CHOICES = [
        (0, 'Novo'),
        (1, 'Pouco usado'),
        (2, 'Usado'),
        (3, 'Muito usado')
    ]
    CATEGORY_CHOICES = [
        (0, 'Livro'),
        (1, 'Tese'),
        (2, 'Revista'),
        (3, 'Artigo'),
        (4, 'Resumo'),
        (5, 'Outro')
    ]
    title = models.CharField('Título', max_length=50)
    author = models.CharField('Autor', max_length=50)
    ISBN = models.CharField('ISBN', max_length=13, blank=True, null=True)
    publishing_company = models.CharField(
        'Editora', max_length=50, blank=True, null=True)
    publication_date = models.DateField(blank=True, null=True)
    conservation = models.IntegerField(choices=CONSERVATION_CHOICES)
    category = models.IntegerField(choices=CATEGORY_CHOICES)
    subject = models.ManyToManyField(Subject)
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Modificado em', auto_now=True)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, blank=True, null=True)
    image = models.ImageField(
        'Image', upload_to='materials/')
    deleted = models.IntegerField(default=0)
    deleted_at = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return self.title


class Ad(models.Model):
    TYPE_CHOICES = [
        (0, 'Venda'),
        (1, 'Doação'),
        (2, 'Empréstimo')
    ]

    duration = models.IntegerField(null=True, blank=True)
    address = models.CharField('Endereço', max_length=200)
    latitude = models.FloatField()
    longitude = models.FloatField()
    price = models.DecimalField('Preço', max_digits=5, decimal_places=2)
    loan_start = models.DateField(null=True, blank=True)
    material = models.OneToOneField(Material, on_delete=models.CASCADE)
    ad_type = models.IntegerField(choices=TYPE_CHOICES)
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Modificado em', auto_now=True)
    request_accepted = models.ForeignKey(
        'Request', related_name='request_accepted', on_delete=models.CASCADE, blank=True, null=True)

    deleted = models.IntegerField(default=0)
    deleted_at = models.IntegerField(blank=True, null=True)

    class Meta:
        def __str__(self):
            return self.material.title


class Request(models.Model):
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Modificado em', auto_now=True)


class Complaint(models.Model):
    COMPLAINT_CHOICES = [
        (0, 'Conteúdo impróprio'),
        (1, 'Conteúdo não educacional'),
        (2, 'Outro')
    ]
    message = models.TextField(null=True, blank=True)
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    complaint_type = models.IntegerField(choices=COMPLAINT_CHOICES)

materials/forms.py
from django import forms
from.models import Material


class MaterialForm(forms.ModelForm):
    class Meta:
        model = Material
        fields = ['title', 'author', 'ISBN', 'publishing_company',
                  'publication_date', 'conservation', 'category', 'subject', 'image']

materials/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import MaterialForm
from .models import Material, Ad, Subject, Request
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.


@login_required
def newMaterial(request):
    if request.method == 'POST':
        form = MaterialForm(request.POST, request.FILES)
        if form.is_valid():
            form.instance.user = request.user
            form.save()
            messages.success(request, 'Material cadastrado!')
            # messages.warning(request, 'exemplo Aviso!')
            # messages.error(request, 'exemplo Erro!')
            # messages.info(request, 'exemplo Info!')
            return redirect("materials:list_material")
        else:
            messages.warning(request, 'Erro no cadastro')
    else:
        form = MaterialForm()
        return render(request, 'materials/new_material.html',  {'form': form})


@login_required
def editMaterial(request, pk):
    material = get_object_or_404(Material, pk=pk)
    if(material.user != request.user):
        messages.error(request, 'Este material não lhe pertence')
        return redirect('materials:list_material')
    if(material.deleted == 1):
        messages.error(request, 'Este material foi removido')
        return redirect('materials:list_material')
    if request.method == "POST":
        form = MaterialForm(request.POST, instance=material)
        if form.is_valid():
            subjects = request.POST.getlist('subject')
            material = form.save(commit=False)
            material.user = request.user
            material.subject.clear()

            for subject in subjects:
                sub = Subject.objects.filter(id=subject).first()
                material.subject.add(sub)
            material.save()
            messages.success(request, 'Material atualizado com sucesso!')
            return redirect('materials:list_material')
    else:
        form = MaterialForm(instance=material)

    return render(request, 'materials/edit_material.html',
                  {'form': form, 'pk': pk, 'title': material.title, 'author': material.author})
# completar return


def excluirMaterial(request, pk):
    material = get_object_or_404(Material, pk=pk)

    if(material.user != request.user):
        messages.error(request, 'Este material não lhe pertence')
        return redirect('materials:list_material')

    if(material.deleted == 1):
        messages.error(request, 'Este material foi removido')
        return redirect('materials:list_material')

    ad = Ad.objects.filter(material_id=pk)

    if (ad):
        messages.error(
            request, 'Material possui um Anúncio, primeiro remova-o')
        return redirect('materials:list_material')
    else:
        messages.success(request, 'Material deletado com sucesso')
        material.deleted = 1
        material.save()
        return redirect('materials:list_material')


@login_required
def ListMaterials(request):
    materials = Material.objects.filter(user=request.user, deleted=0)
    anuncios = Ad.objects.all()
    anunciados = []
    for ad in anuncios:
        for m in materials:
            if m.pk == ad.material.pk and ad.deleted == 0:
                anunciados.append(ad.material)

    return render(request, 'materials/list_material.html',  {'materials': materials, 'anunciados': anunciados})


@login_required
def minhasSolicitacoes(request):
    Solicitacoes = Request.objects.filter(user=request.user)
    materials = []
    return render(request, 'materials/minhas_solicitacoes.html',  {'solicitacoes': Solicitacoes})


@login_required
def solicitacoesRecebidas(request):
    Requests = Request.objects.all()
    Solicitacoes = []

    for req in Requests:
        # Se o dono do material for o cara que ta acessando
        # vai pegar todos as soand req.ad.deleted == 0licitacoes pros anuncios cujo o material é dele
        # mas acho que essa view seria interessante fazer algo em pegar todos os anuncios
        # e depois verificar as solicitacoes pra cada anuncios, daí da pra iterar e mostrar as solicitações
        # pros anuncios isoladas

        # resumindo seria uma pagina mostrando 'meus anuncios' e podendo clicar pra ver as solicitacoes dele
        if req.ad.material.user == request.user and req.ad.deleted == 0:
            Solicitacoes.append(req)

    return render(request, 'materials/solicitacoes_recebidas.html',  {'solicitacoes': Solicitacoes})

templates/materials/edit_material.html
{% extends 'base.html' %} {% load static %}
{% block title %} Editar {% endblock %}
{% block content %}
<div class="container">
  <div class="card-panel">
    <div class="card-content">
      <h4 class="header">Material</h4>
    </div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button class="btn waves-effect waves-light green" type="submit">
        <i class="material-icons right">send</i>Salvar alterações
      </button>
      <a href="{% url 'materials:list_material' %}" class="btn grey lighten-1">Cancelar</a>
    </form>
  </div>
</div>
{% endblock %}

templates/materials/list_material.html
{% extends 'base.html' %} {% load static %}

{% block title %} Materiais {% endblock %} {% block content %}

<div class="row">

  <h1 class="center">Meus Materiais</h1>

  {% for material in materials %}
  <div class="col m4">
    <div class="card">
      <div class="card-image">
        <img src="{{ material.image.url }}" alt="img">
        <div class="row center">
          <a href="{% url 'ads:ad_url' material.pk 0 %}" class="btn-floating btn waves-effect waves-light green"
            title="Vender"><i class="material-icons">attach_money</i></a>
          <a href="{% url 'ads:ad_url' material.pk 1 %}" class="btn-floating btn waves-effect waves-light green"
            title="Doar"><i class="material-icons">loyalty</i></a>
          <a href="{% url 'ads:ad_url' material.pk 2 %}" class="btn-floating btn waves-effect waves-light green"
            title="Emprestar"><i class="material-icons">history</i></a>
          <a href="{% url 'materials:edit_material' material.pk %}"
            class="btn-floating btn waves-effect waves-light red" title="Editar"><i class="material-icons">edit</i></a>
          <a href="{% url 'materials:excluir_material' material.pk %}"
            class="btn-floating btn waves-effect waves-light red" title="Excluir"><i
              class="material-icons">delete</i></a>
        </div>
      </div>
      <div class="card-content">
        <span class="card-title center">{{ material.title }}</span>
        {% for anunciado in anunciados %}
        {% if anunciado.pk == material.pk %}
        <center><a href="{% url 'ads:vermais_url' material.pk %}"><b>ANUNCIADO</b></a></center>
        <center><a href="{% url 'ads:excluir_url' anunciado.pk %}">Remover anúncio</a></center>
        {% endif %}
        {% endfor %}
        <p>Autor: {{ material.author }}</p>
        <p>ISBN: {{ material.ISBN }}</p>
        <p>Editora: {{ material.publishing_company }}</p>
        <p>Estado de conservação: {{ material.get_conservation_display }}</p>
        <p>Tipo: {{ material.get_category_display }}</p>
        <p>
          Assuntos: {% for subject in material.subject.all %}{{ subject }},
          {% endfor %}
        </p>
        <p>Criação: {{ material.created_at }}</p>

      </div>
    </div>
  </div>
  {% endfor %}

</div>
<div class="fixed-action-btn">
  <a href="{% url "materials:new_material" %}" class="btn-floating btn-large red pulse" data-position="bottom"
    data-tooltip="Novo material"><i class="material-icons">add</i></a>
</div>
{% endblock %}

templates/materials/minhas_solicitacoes.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Solicitações {% endblock %}

{% block content %}


<center>
  <h3>Minhas Solicitações</h3>
</center>

{% for solicitacao in solicitacoes %}

<div class="col m4">
  <div class="card">
    <div class="card-content">
      <span class="card-title center">
        <p class="flow-text truncate">
          <a target="_blank"
            href="{% url 'ads:vermais_url'  solicitacao.ad.material.pk %}">{{ solicitacao.ad.material.title }} </a>
        </p>
      </span>
      <p>Tipo anúncio: {{ solicitacao.ad.get_ad_type_display }}</p>
      <p>Dono do anúncio: {{ solicitacao.ad.material.user.username }}</p>
      <p class="left">Status:</p>
      {% if solicitacao.ad.request_accepted == None %}
      <i class="material-icons orange-text">
        access_time
      </i><span class="badge left orange white-text">Aguardando</span>
      {% elif solicitacao.ad.request_accepted.user == user %}
      <i class="material-icons green-text">
        check_circle
      </i><span class="badge left green white-text"> Aceita</span>
      {% else %} <i class="material-icons red-text">
        report
      </i><span class="badge left red white-text">Outra solicitação foi aceita</span>
      {% endif %}
      {% if solicitacao.ad.request_accepted == None or solicitacao.ad.request_accepted.user == user %}
      {% endif %}

      <center>
        <div class="card-action">
          <a href="{% url 'ads:negociacao_url' solicitacao.ad.pk %}" class="btn btn-primary green center" role="button"> <i
              class="material-icons white-text">
              chat
            </i> Negociação</a>
        </div>
      </center>
    </div>
  </div>
</div>

{% endfor %} {% endblock %}

templates/materials/new_material.html
{% extends 'base.html' %} {% load static %}
{% block title %} Novo material
{% endblock %} {% block content %}

<style>
  label {
    color: black;
  }
</style>

<div class="container">
  <div class="card-panel">
    <div class="card-content">
      <h4 class="header center" style="color:white; text-shadow: 2px 2px 3px #000">Material</h4>
    </div>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <p><label for="id_title">Título:</label> <input type="text" name="title" id="id_title" required="" maxlength="50">
      </p>
      <p><label for="id_author">Autor:</label> <input type="text" name="author" id="id_author" required=""
          maxlength="50"></p>
      <p><label for="id_ISBN">ISBN:</label> <input type="text" name="ISBN" id="id_ISBN" maxlength="13"></p>
      <p><label for="id_publishing_company">Editora:</label> <input type="text" name="publishing_company"
          id="id_publishing_company" maxlength="50"></p>
      <label for="id_publication_date">Publication date:</label>
      <input type="date" name="publication_date" id="id_publication_date">
      <p><label for="id_conservation">Conservação:</label>
        {{ form.conservation }}
      </p>
      <p><label for="id_category">Categoria:</label>
        {{ form.category }}
      </p>
      <p><label for="id_subject">Assunto:</label>
        {{ form.subject }}
      </p>
      <p>
        <div class="file-field input-field">
          <div class="btn">
            <span>Imagem</span>
            <input type="file" name="image" accept="image/*" required="" id="id_image">
          </div>
          <div class="file-path-wrapper">
            <input class="file-path validate" type="text">
          </div>
        </div>
      </p>
      <button class="btn waves-effect waves-light green" type="submit">
        <i class="material-icons right">send</i>Cadastrar
      </button>
      <a href="{% url 'materials:list_material' %}" class="btn grey lighten-1">Cancelar</a>
    </form>
  </div>
</div>

{% endblock %}

templates/materials/solicitacoes_recebidas.html
{% extends 'base.html' %} {% load static %} 
{% block title %} Recebidas {% endblock %} 

{% block content %}

    <center><h3>Solicitações recebidas</h3></center>
    {% for solicitacao in solicitacoes %}
        Material anunciado: {{solicitacao.ad.material.title}} </br>
        tipo do anuncio: {{solicitacao.ad.get_ad_type_display}} </br>
        solicitante: {{solicitacao.user.username}}
        <a
            href="{% url 'ads:negociacao_url' solicitacao.ad.pk %}"
            class="btn btn-primary"
            role="button"
            >Negociação</a
        >
        <br/>
    {% endfor %}
{% endblock %}