ads/urls.py
from django.urls import path
from .views import index, solicitacao, vermais, negociacao, excluir_anuncio, cria_anuncio, meusanuncios, solicitacoesanuncio, aceitar, denuncia
app_name = 'ads'
urlpatterns = [
    path('', index, name="index_url"),
    path('novo/<int:pk>/<int:tipo>', cria_anuncio, name="ad_url"),
    path('excluir/<int:pk>', excluir_anuncio, name="excluir_url"),
    path('vermais/<int:pk>', vermais, name="vermais_url"),
    path('solicitacao/<int:anuncio>/<int:pk>',
         solicitacao, name="solicitacao_url"),
    path('negociacao/<int:pk>', negociacao, name="negociacao_url"),
    path('anuncios/', meusanuncios, name="meus_anuncios"),
    path('solicitacoes/<int:pk>', solicitacoesanuncio,
         name='solicitacoes_anuncio'),
    path('aceitar/<int:ad_pk>/<int:req_pk>', aceitar, name="aceitar"),
    path('denuncia/<int:pk>', denuncia, name="denuncia")
]

bricademy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import home, homemap, sobre
from users import urls as users_urls
from materials import urls as materials_urls
from ads import urls as ads_urls
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('', home, name="home"),
    path('map/', homemap, name="map"),
    path('sobre/', sobre, name="sobre"),
    path('materials/', include(materials_urls)),
    path('users/', include(users_urls)),
    path('ads/', include(ads_urls)),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

users/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from .views import signup
from .views import logout_user, Login, profile, newAddress, update_profile

app_name = 'users'
urlpatterns = [
    path('perfil', profile, name="perfil"),
    path('cadastro', signup, name="signup"),
    path('editar', update_profile, name="update_url"),
    path('login', Login.as_view(), name='login'),
    path('logout', logout_user, name='logout'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html',
                                                                 email_template_name='registration/password_reset_email.html',
                                                                 subject_template_name='registration/password_reset_subject.txt',
                                                                 success_url=reverse_lazy(
                                                                     'users:password_reset_done')
                                                                 ), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html',
                                                                                                 success_url=reverse_lazy('users:password_reset_complete')), name='password_reset_confirm'),
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    path('endereco', newAddress, name='new_address'),
]

ads/models.py
from django.db import models

# Create your models here.

materials/models.py
from django.db import models
from django.contrib.auth.models import User


class Subject(models.Model):
    subject = models.CharField('Assunto', max_length=100)
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Modificado em', auto_now=True)

    def __str__(self):
        return self.subject


class Material(models.Model):
    CONSERVATION_CHOICES = [
        (0, 'Novo'),
        (1, 'Pouco usado'),
        (2, 'Usado'),
        (3, 'Muito usado')
    ]
    CATEGORY_CHOICES = [
        (0, 'Livro'),
        (1, 'Tese'),
        (2, 'Revista'),
        (3, 'Artigo'),
        (4, 'Resumo'),
        (5, 'Outro')
    ]
    title = models.CharField('Título', max_length=50)
    author = models.CharField('Autor', max_length=50)
    ISBN = models.CharField('ISBN', max_length=13, blank=True, null=True)
    publishing_company = models.CharField(
        'Editora', max_length=50, blank=True, null=True)
    publication_date = models.DateField(blank=True, null=True)
    conservation = models.IntegerField(choices=CONSERVATION_CHOICES)
    category = models.IntegerField(choices=CATEGORY_CHOICES)
    subject = models.ManyToManyField(Subject)
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Modificado em', auto_now=True)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, blank=True, null=True)
    image = models.ImageField(
        'Image', upload_to='materials/')
    deleted = models.IntegerField(default=0)
    deleted_at = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return self.title


class Ad(models.Model):
    TYPE_CHOICES = [
        (0, 'Venda'),
        (1, 'Doação'),
        (2, 'Empréstimo')
    ]

    duration = models.IntegerField(null=True, blank=True)
    address = models.CharField('Endereço', max_length=200)
    latitude = models.FloatField()
    longitude = models.FloatField()
    price = models.DecimalField('Preço', max_digits=5, decimal_places=2)
    loan_start = models.DateField(null=True, blank=True)
    material = models.OneToOneField(Material, on_delete=models.CASCADE)
    ad_type = models.IntegerField(choices=TYPE_CHOICES)
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Modificado em', auto_now=True)
    request_accepted = models.ForeignKey(
        'Request', related_name='request_accepted', on_delete=models.CASCADE, blank=True, null=True)

    deleted = models.IntegerField(default=0)
    deleted_at = models.IntegerField(blank=True, null=True)

    class Meta:
        def __str__(self):
            return self.material.title


class Request(models.Model):
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Modificado em', auto_now=True)


class Complaint(models.Model):
    COMPLAINT_CHOICES = [
        (0, 'Conteúdo impróprio'),
        (1, 'Conteúdo não educacional'),
        (2, 'Outro')
    ]
    message = models.TextField(null=True, blank=True)
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    complaint_type = models.IntegerField(choices=COMPLAINT_CHOICES)

ads/forms.py
from django import forms
from materials.models import Ad, Complaint


class AdVendaForm(forms.ModelForm):
    class Meta:
        model = Ad
        fields = ['price', 'address', 'latitude', 'longitude']
        widgets = {'latitude': forms.HiddenInput(
        ), 'longitude': forms.HiddenInput()}


class AdEmprestimoForm(forms.ModelForm):
    class Meta:
        model = Ad
        fields = ['address', 'latitude', 'longitude']
        widgets = {'latitude': forms.HiddenInput(
        ), 'longitude': forms.HiddenInput()}


class AdDoacaoForm(forms.ModelForm):
    class Meta:
        model = Ad
        fields = ['address', 'latitude', 'longitude']
        widgets = {'latitude': forms.HiddenInput(
        ), 'longitude': forms.HiddenInput()}


class AdComplaintForm(forms.ModelForm):
    class Meta:
        model = Complaint
        fields = ['message', 'complaint_type']

ads/views.py
from django.shortcuts import render, get_object_or_404, redirect
from materials.models import Ad, Material, Request
from django.http import HttpResponseNotFound
from .forms import AdVendaForm, AdDoacaoForm, AdEmprestimoForm, AdComplaintForm
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required


def index(request):
    # anuncios_venda = Ad.objects.filter(ad_type=0)
    # materiais_venda = []
    # for an in anuncios_venda:
    #     materiais_venda.append(an.material)
    # return render(request, 'home.html', {'vendas': materiais_venda})
    anuncios = Ad.objects.all()
    material = []
    tipos = []
    for ad in anuncios:
        if(ad.deletado == 0):
            material.append(ad.material)
            tipos.append(ad.ad_type)
    todos = list(zip(material, tipos))
    todos.sort(key=lambda x: x[0])
    return render(request, 'home.html', {'materiais': todos})


@login_required
def cria_anuncio(request, pk, tipo):

    # Verifica se já existe um anúncio para aquele material. Se nao tiver anuncia, senão retorna direto.
    ads = Ad.objects.filter(material=pk)
    if not ads:
        material = get_object_or_404(Material, pk=pk)
        if(material.user != request.user):
            messages.error(request, 'Este material não lhe pertence')
            return redirect('home')
        if(material.deleted == 1):
            messages.error(request, 'Este material foi removido')
            return redirect('home')
        if(request.method == 'GET'):
            if(tipo == 0):
                form = AdVendaForm()
            elif(tipo == 1):
                form = AdDoacaoForm()
            else:
                form = AdEmprestimoForm()
            return render(request, 'ads/new.html', {'form': form, 'token': settings.MAPBOX_TOKEN})

        elif(request.method == 'POST'):

            if(tipo == 0):
                form = AdVendaForm(request.POST)
            elif(tipo == 1):
                form = AdDoacaoForm(request.POST)
            else:
                form = AdEmprestimoForm(request.POST)

            if not form.data['address']:
                messages.error(request, 'Selecione um endereço para o anúncio')
                return render(request, 'ads/new.html', {'form': form, 'token': settings.MAPBOX_TOKEN})

            if form.is_valid():
                ad = form.save(commit=False)
                ad.material = material
                ad.ad_type = tipo

                if ad.price == None:
                    ad.price = 0
                ad.save()
                messages.success(request, 'Anúncio criado com sucesso!!')
    else:
        messages.warning(request, 'Material já anunciado')

    return redirect('home')


def excluir_anuncio(request, pk):

    solicitacoes = Request.objects.all()

    # for s in solicitacoes:
    #    if s.ad.pk == pk:
    #        messages.warning(
    #            request, 'Você precisa responder as solicitações sobre este anúncio')
    #        return redirect('materials:list_material')

    anuncio = get_object_or_404(Ad, material=pk)
    if anuncio.request_accepted is not None:
        messages.error(
            request, 'Você já aceitou uma solicitação, não é possível remover')
        return redirect('materials:list_material')
    else:
        anuncio.delete()
        # anuncio.deleted = 1
        # anuncio.save()
        messages.success(request, 'Anúncio deletado com sucesso')
        return redirect('materials:list_material')


# recebe o tipo de anuncio e o id do material
@login_required
def vermais(request, pk):
    anuncio = get_object_or_404(Ad, material_id=pk)
    tipo = anuncio.ad_type
    if(anuncio.deleted == 1):
        messages.error(request, 'Este anuncio foi removido pelo dono')
        return redirect('home')

    return render(request, 'ads/vermais.html', {'material': anuncio.material, 'anuncio': anuncio, 'tipo': tipo, 'token': settings.MAPBOX_TOKEN})


@login_required
def solicitacao(request,  anuncio, pk):
    anuncio = get_object_or_404(Ad, material_id=pk)
    if(anuncio.deleted == 1):
        messages.error(request, 'Este anúncio foi removido pelo dono')
        return redirect('home')

    solicitacao = Request.objects.filter(ad=anuncio, user=request.user)

    if(solicitacao):
        messages.warning(
            request, 'Você já fez uma solicitação para esse material')
        return redirect('home')
    else:
        solicitacao = Request.objects.create(ad=anuncio, user=request.user)
        messages.success(
            request, 'Solicitação enviada com sucesso')
    return render(request, 'ads/venda.html', {'anuncio': anuncio, 'token': settings.MAPBOX_TOKEN})


@login_required
def negociacao(request, pk):
    anuncio = get_object_or_404(Ad, pk=pk)
    return render(request, 'ads/venda.html', {'anuncio': anuncio, 'token': settings.MAPBOX_TOKEN})


@login_required
def meusanuncios(request):
    todosanuncios = Ad.objects.all()
    meusanuncios = []
    for anuncio in todosanuncios:
        if anuncio.material.user == request.user:
            meusanuncios.append(anuncio)
    return render(request, 'ads/meusanuncios.html', {'anuncios': meusanuncios})


def solicitacoesanuncio(request, pk):
    anuncio = get_object_or_404(Ad, pk=pk)
    todassolicitacoes = Request.objects.all()
    solicitacoes = []
    for solicitacao in todassolicitacoes:
        if solicitacao.ad == anuncio:
            solicitacoes.append(solicitacao)
            # return render
    return render(request, 'ads/solicitacoes_recebidas.html',  {'solicitacoes': solicitacoes, 'anuncio': anuncio})


def aceitar(request, ad_pk, req_pk):
    anuncio = get_object_or_404(Ad, pk=ad_pk)
    solicitacao = get_object_or_404(Request, pk=req_pk)
    if(anuncio.material.user != request.user):
        messages.error(request, 'Este material não lhe pertence')
        return redirect('ads:meus_anuncios')
    if(anuncio.request_accepted is not None):
        messages.error(request, 'Você já aceitou uma solicitação')
        return redirect('ads:meus_anuncios')
    messages.success(request, 'Solicitação aceita')
    anuncio.request_accepted = solicitacao
    anuncio.save()
    return redirect('ads:meus_anuncios')


def denuncia(request, pk):
    anuncio = get_object_or_404(Ad, pk=pk)
    if(request.method == 'GET'):
        form = AdComplaintForm()
        return render(request, 'ads/denuncia.html', {'form': form, 'anuncio': anuncio})
    else:
        try:
            form = AdComplaintForm(request.POST)
            if form.is_valid():
                denuncia = form.save(commit=False)
                denuncia.ad = anuncio
                form.save()
                messages.success(request, 'Denúncia enviada')
        except:
            messages.error(request, 'Falha ao enviar denúncia')
        finally:
            return redirect('ads:vermais_url', pk=anuncio.material.pk)

templates/ads/denuncia.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Denúncia
{% endblock %}
{% block content %}

<center>
  <h3>Realizar Denúncia Sobre {{ anuncio.material.title }}</h3>
</center>
<div class="container">
  <div class="card-panel">
    <div class="card-content">
      <form method="post">
        {% csrf_token %}
        <textarea class="materialize-textarea" name="message" id="id_message" class="white" cols="40" rows="100"
          placeholder="Descreva detalhadamente e especificamente os motivos dessa denúncia..."></textarea>
        <br><br>
        <label for="id_complaint_type" class="">Tipo de Reclamação:</label>
        {{ form.complaint_type }}
        <center>
          <br>
          <button class="btn btn-primary" type="submit">
            <i class="material-icons right">send</i>Enviar Denúncia
          </button>
        </center>
      </form>
    </div>
  </div>
</div>

{% endblock %}

templates/ads/doacao.html
{% extends 'base.html' %} {% load static %} 
{% block title %} Doação {% endblock %} {% block content %}

Aqui negociação sobre Doação

{% endblock %}

templates/ads/emprestimo.html
{% extends 'base.html' %} {% load static %} 
{% block title %} Empréstimo {% endblock %} {% block content %}

Aqui negociação sobre Empréstimo

{% endblock %}

templates/ads/list_map.html
{% extends 'base.html' %} 
{% load static %} 
{% block title %}
Mapa
{% endblock %}
{% block content %} 
{% block head %}
<script src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.3.0/mapbox-gl-geocoder.min.js"></script>
<link
  rel="stylesheet"
  href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.3.0/mapbox-gl-geocoder.css"
  type="text/css"
/>
{% endblock head %}

<style>
  .filter-ctrl {
    top: 10px;
    right: 10px;
    z-index: 1;
    width: 180px;
  }

  .filter-ctrl input[type="text"] {
    font: 20px "Helvetica Neue", Arial, Helvetica, sans-serif;
    width: 100%;
    border: 0;
    background-color: #c9c9c9;
    height: 40px;
    margin: 0;
    color: rgba(0, 0, 0, 0.5);
    padding: 10px;
    box-shadow: 0 0 0 2px rgba(0, 0, 0, 0.1);
    border-radius: 3px;
  }
</style>
<div class="filter-ctrl">
  <input
    id="filter-input"
    type="text"
    name="filter"
    placeholder="Buscar por título"
  />
</div>
Anúncios: <input readonly id="encontrados" />

<div id="map" style="width: 100%; height:500px;"></div>

<script>
    navigator.geolocation.getCurrentPosition(function(position) {
      mapboxgl.accessToken = "{{ token }}";
      var MarkFilter = []; // Will contain a list used to filter against.
      var AllMarks = [];
      var label = document.getElementById("encontrados");
      var filterInput = document.getElementById('filter-input');
      var map = new mapboxgl.Map({
        container: "map", // Container ID
        style: "mapbox://styles/mapbox/navigation-guidance-day-v2",

        center: [position.coords.longitude, position.coords.latitude], // Starting position [lng, lat]
        zoom: 13 // Starting zoom level
      });


      map.addControl(new mapboxgl.GeolocateControl({
        positionOptions: {
        enableHighAccuracy: true
      },
        trackUserLocation: true
      }));

      var geojson = {
        id: "places",
        type: "FeatureCollection",
        features: [
        {% for anuncio in anuncios %}
        {
            type: "Feature",
            properties: {
              adType: {{anuncio.ad_type}},
              title: "{{anuncio.material.title}}",
              id: {{anuncio.pk}},
              idMat: {{anuncio.material.id}},
              tipoAnuncio: "{{anuncio.get_ad_type_display}}",
              iconSize: [20, 20],
              tipo: {{anuncio.material.category}},
            },
            geometry: {
              type: "Point",
              coordinates: [{{anuncio.longitude}}, {{anuncio.latitude}}],
            }
          },
          {% endfor %}
        ]
      };

      label.value = geojson.features.length;
      geojson.features.forEach(function(marker) {
        // create a DOM element for the marker

        var el = document.createElement("div");
        el.className = "marker";
        el.style.backgroundImage = "url(http://localhost:8000/static/images/map/livro.svg)";

        el.style.width = marker.properties.iconSize[0] + "px";
        el.style.height = marker.properties.iconSize[1] + "px";
        marker.el = el;
        AllMarks.push(marker);
        // add marker to map
        new mapboxgl.Marker(el).setLngLat(marker.geometry.coordinates).setPopup(new mapboxgl.Popup({ offset: 25 }) // add popups
        .setHTML('<b>Título</b>: ' + marker.properties.title + '<p><b>Tipo: </b>'+ marker.properties.tipoAnuncio +  '</p><p><a href=\"/ads/vermais/'+marker.properties.adType+'/'+marker.properties.idMat +"\">" + "<span class='badge red white-text'>Ver mais</span>" + '</a></p>')).addTo(map);});      // Create a popup, but don't add it to the map yet.


      var popup = new mapboxgl.Popup({
        closeButton: false,
        closeOnClick: false
      });

      map.on("load", "places", function(e) {
        // Change the cursor style as a UI indicator.
        map.getCanvas().style.cursor = "pointer";

        var coordinates = e.features[0].geometry.coordinates.slice();
        var description = e.features[0].properties.description;

        // Ensure that if the map is zoomed out such that multiple
        // copies of the feature are visible, the popup appears
        // over the copy being pointed to.
        while (Math.abs(e.lngLat.lng - coordinates[0]) > 180) {
          coordinates[0] += e.lngLat.lng > coordinates[0] ? 360 : -360;
        }

        // Populate the popup and set its coordinates
        // based on the feature found.
        popup
          .setLngLat(coordinates)
          .setHTML(description)
          .addTo(map);
      });


      filterInput.addEventListener('keyup', function(e) {
      var value = e.target.value.trim();
      geojson.features.forEach(function(marker) {
        if(!(marker.properties.title.indexOf(value) !== -1)){
          //MarkFilter.push(marker);
          //se a marca nao tiver nada com o texto digitado remove

          var removeIndex = AllMarks.indexOf(marker);
          if(removeIndex > -1){
            AllMarks.splice(removeIndex, 1);
            marker.el.remove();
          }

        }else{
          if(!(AllMarks.includes(marker))){
           var el = document.createElement("div");
           el.className = "marker";
           el.style.backgroundImage = "url(http://localhost:8000/static/images/map/livro.svg)";

           el.style.width = marker.properties.iconSize[0] + "px";
           el.style.height = marker.properties.iconSize[1] + "px";

           marker.el = new mapboxgl.Marker(el).setLngLat(marker.geometry.coordinates).setPopup(new mapboxgl.Popup({ offset: 25 }) // add popups
         .setHTML('<b>Título</b>: ' + marker.properties.title + '<p><b>Tipo: </b>'+ marker.properties.tipoAnuncio +  '</p><p><a href=\"/ads/vermais/'+marker.properties.adType+'/'+marker.properties.idMat +"\">" + "<span class='badge red white-text'>Ver mais</span>" + '</a></p>'));
           marker.el.addTo(map);
           AllMarks.push(marker);
         }
        }
      });
      label.value = AllMarks.length;

  });

    });
</script>
{% endblock %}

templates/ads/meusanuncios.html
{% extends 'base.html' %} {% load static %} {% block title %} Meus Anúncios 
{% endblock %} {% block content %}

<center><h3>Meus Anúncios</h3></center>

{% for anuncio in anuncios %} 
<b>Material:</b> {{ anuncio.material.title }} <br />
<b>Assuntos:</b> {% for subject in anuncio.material.subject.all %}{{ subject }}, {% endfor %}</br>
<b>Tipo anúncio:</b> {{ anuncio.get_ad_type_display }} <br />
<br />
<a
  href="{% url 'ads:solicitacoes_anuncio' anuncio.pk %}"
  class="btn btn-primary"
  role="button"
  >Solicitações</a
>
<br />
<br />
<hr>
{% endfor %} {% endblock %}

templates/ads/solicitacoes_recebidas.html
{% extends 'base.html' %} {% load static %} {% block title %} Solicitações recebidas 
{% endblock %} {% block content %}

<center>
  <h3>Solicitações de {{ anuncio.material.title }}</h3>
</center>

<b>Assuntos:</b> {% for subject in anuncio.material.subject.all %}{{ subject }}, {% endfor %}</br>
<b>Tipo anúncio:</b> {{ anuncio.get_ad_type_display }} <br />

<br />
{% for solicitacao in solicitacoes %} <b>Solicitante:</b>
{{ solicitacao.user.username }}
{% if anuncio.request_accepted == solicitacao %}
<i class="material-icons right green-text">
  check_circle
  </i><span class="badge green white-text">Solicitação aceita</span>
  <a
  href="{% url 'ads:negociacao_url' solicitacao.ad.pk %}"
  class="btn-small right  btn-primary"
  role="button"
  >Negociação</a
>
{% endif %}
{% if anuncio.request_accepted != solicitacao and anuncio.request_accepted is not None %}
<i class="material-icons right red-text">
  report
  </i><span class="badge red white-text">Outra solicitacao aceita</span>

{% endif %}
{% if anuncio.request_accepted is None %}
<a
  href="{% url 'ads:aceitar' anuncio.pk solicitacao.pk %}"
  class="btn-small right btn-primary green"
  role="button"
  >Aceitar</a
>
<a
  href="{% url 'ads:negociacao_url' solicitacao.ad.pk %}"
  class="btn-small right  btn-primary"
  role="button"
  >Negociação</a
>
{% endif %}


<br />
<br /><hr/>
<br />
{% endfor %}
{% if not solicitacoes %}
<h5>Não há solicitações para esse anúncio</h5>
<br/>
<a
  href="{% url 'ads:meus_anuncios' %}"
  class="btn-small  btn-primary"
  role="button"
  >Voltar</a
>
{% endif %}

{% endblock %}

templates/ads/vermais.html
{% extends 'base.html' %} {% load static %}
{% block title %} Ver mais {% endblock %} {% block content %}

{% if tipo == 0 %}

<div class="card-reveal">
  <span class="card-title grey-text text-darken-4"><b>
      <h2>{{ material.title }}</h2>
      <h4>R${{anuncio.price}}</h4>
    </b></span>
  <hr>

  {% else %}

  <div class="card-reveal">
    <span class="card-title grey-text text-darken-4"><b>
        <h2>{{ material.title }}</h2>
      </b></span>
    <hr>

    {% endif %}

    <p><b>Autor:</b> {{ material.author }}<br>
      <b>ISBN:</b> {{ material.ISBN }}<br>
      <b>Editora:</b> {{ material.publishing_company }}<br>
      <b>Conservação:</b> {{ material.get_conservation_display }}<br>
      <b>Tipo:</b> {{ material.get_category_display }}<br>
      <b>Assuntos:</b> {% for subject in material.subject.all %}
      {{ subject }}, {% endfor %}
    </p>
  </div>

  {% if material.user.pk == user.pk %}
  <center>
    <b>Este material é seu.</b>
  </center>
  {% else %}
  {% if user.is_authenticated %}
  <center>
    <div class="card-action"><a href="{% url 'ads:solicitacao_url' anuncio.pk material.pk %}"
        class="btn btn-primary green" role="button"><i class="material-icons left">library_add</i>Comprar</a>
      <a href="{% url 'ads:denuncia' anuncio.pk  %}" class="btn btn-primary" role="button"><i
          class="material-icons left">report</i>Denunciar</a>
    </div>
    <br>
  </center>

  {% else %}
  <center>
    <div class="card-action">
      <a href="{% url 'users:login' %}" class="btn btn-primary green" role="button"><i
        class="material-icons left">library_add</i>Comprar</a>
    </div>
  </center>
  {% endif %}
  {% endif %}

  <hr>
  <h4>Ver no mapa:</h4>
  Endereço: {{anuncio.address}}
  <script
    src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.3.0/mapbox-gl-geocoder.min.js"></script>
  <link rel="stylesheet"
    href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.3.0/mapbox-gl-geocoder.css"
    type="text/css" />

  <div id="map" style="height: 500px;"></div>

  <script>
    navigator.geolocation.getCurrentPosition(function (position) {
      mapboxgl.accessToken = "{{ token }}";
      var map = new mapboxgl.Map({
        container: "map", // Container ID
        style: "mapbox://styles/mapbox/navigation-guidance-day-v2",

        center: [{{ anuncio.longitude }}, {{ anuncio.latitude }}], // Starting position [lng, lat]
      zoom: 15 // Starting zoom level
    });


    map.addControl(new mapboxgl.GeolocateControl({
      positionOptions: {
        enableHighAccuracy: true
      },
      trackUserLocation: true
    }));

    var geojson = {
      id: "places",
      type: "FeatureCollection",
      features: [
        {
          type: "Feature",
          properties: {
            iconSize: [20, 20],
          },
          geometry: {
            type: "Point",
            coordinates: [{{ anuncio.longitude }}, {{ anuncio.latitude }}],
          }
        },
      ]
    };


    geojson.features.forEach(function (marker) {
      // create a DOM element for the marker
      var el = document.createElement("div");
      el.className = "marker";
      el.style.backgroundImage = "url(http://localhost:8000/static/images/map/livro.svg)";

      el.style.width = marker.properties.iconSize[0] + "px";
      el.style.height = marker.properties.iconSize[1] + "px";


      // add marker to map
      new mapboxgl.Marker(el).setLngLat(marker.geometry.coordinates).addTo(map);
    });      // Create a popup, but don't add it to the map yet.
  });
  </script>


  {% endblock %}