ads/urls.py
from django.urls import path
from .views import index, solicitacao, vermais, negociacao, excluir_anuncio, cria_anuncio, meusanuncios, solicitacoesanuncio, aceitar, denuncia
app_name = 'ads'
urlpatterns = [
    path('', index, name="index_url"),
    path('novo/<int:pk>/<int:tipo>', cria_anuncio, name="ad_url"),
    path('excluir/<int:pk>', excluir_anuncio, name="excluir_url"),
    path('vermais/<int:pk>', vermais, name="vermais_url"),
    path('solicitacao/<int:anuncio>/<int:pk>',
         solicitacao, name="solicitacao_url"),
    path('negociacao/<int:pk>', negociacao, name="negociacao_url"),
    path('anuncios/', meusanuncios, name="meus_anuncios"),
    path('solicitacoes/<int:pk>', solicitacoesanuncio,
         name='solicitacoes_anuncio'),
    path('aceitar/<int:ad_pk>/<int:req_pk>', aceitar, name="aceitar"),
    path('denuncia/<int:pk>', denuncia, name="denuncia")
]

bricademy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import home, homemap, sobre
from users import urls as users_urls
from materials import urls as materials_urls
from ads import urls as ads_urls
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('', home, name="home"),
    path('map/', homemap, name="map"),
    path('sobre/', sobre, name="sobre"),
    path('materials/', include(materials_urls)),
    path('users/', include(users_urls)),
    path('ads/', include(ads_urls)),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

materials/urls.py
from django.urls import path
from .views import newMaterial, minhasSolicitacoes, solicitacoesRecebidas, ListMaterials, editMaterial, excluirMaterial

app_name = 'materials'
urlpatterns = [
    path('new', newMaterial, name="new_material"),
    path('list', ListMaterials, name="list_material"),
    path('solicitacoes', minhasSolicitacoes, name="minhas_solicitacoes"),
    path('recebidas', solicitacoesRecebidas, name="solicitacoes_recebidas"),
    path('edit/<int:pk>', editMaterial, name="edit_material"),
    path('excluir/<int:pk>', excluirMaterial, name="excluir_material")
]

users/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from .views import signup
from .views import logout_user, Login, profile, newAddress, update_profile

app_name = 'users'
urlpatterns = [
    path('perfil', profile, name="perfil"),
    path('cadastro', signup, name="signup"),
    path('editar', update_profile, name="update_url"),
    path('login', Login.as_view(), name='login'),
    path('logout', logout_user, name='logout'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html',
                                                                 email_template_name='registration/password_reset_email.html',
                                                                 subject_template_name='registration/password_reset_subject.txt',
                                                                 success_url=reverse_lazy(
                                                                     'users:password_reset_done')
                                                                 ), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html',
                                                                                                 success_url=reverse_lazy('users:password_reset_complete')), name='password_reset_confirm'),
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    path('endereco', newAddress, name='new_address'),
]

materials/models.py
from django.db import models
from django.contrib.auth.models import User


class Subject(models.Model):
    subject = models.CharField('Assunto', max_length=100)
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Modificado em', auto_now=True)

    def __str__(self):
        return self.subject


class Material(models.Model):
    CONSERVATION_CHOICES = [
        (0, 'Novo'),
        (1, 'Pouco usado'),
        (2, 'Usado'),
        (3, 'Muito usado')
    ]
    CATEGORY_CHOICES = [
        (0, 'Livro'),
        (1, 'Tese'),
        (2, 'Revista'),
        (3, 'Artigo'),
        (4, 'Resumo'),
        (5, 'Outro')
    ]
    title = models.CharField('Título', max_length=50)
    author = models.CharField('Autor', max_length=50)
    ISBN = models.CharField('ISBN', max_length=13, blank=True, null=True)
    publishing_company = models.CharField(
        'Editora', max_length=50, blank=True, null=True)
    publication_date = models.DateField(blank=True, null=True)
    conservation = models.IntegerField(choices=CONSERVATION_CHOICES)
    category = models.IntegerField(choices=CATEGORY_CHOICES)
    subject = models.ManyToManyField(Subject)
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Modificado em', auto_now=True)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, blank=True, null=True)
    image = models.ImageField(
        'Image', upload_to='materials/')
    deleted = models.IntegerField(default=0)
    deleted_at = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return self.title


class Ad(models.Model):
    TYPE_CHOICES = [
        (0, 'Venda'),
        (1, 'Doação'),
        (2, 'Empréstimo')
    ]

    duration = models.IntegerField(null=True, blank=True)
    address = models.CharField('Endereço', max_length=200)
    latitude = models.FloatField()
    longitude = models.FloatField()
    price = models.DecimalField('Preço', max_digits=5, decimal_places=2)
    loan_start = models.DateField(null=True, blank=True)
    material = models.OneToOneField(Material, on_delete=models.CASCADE)
    ad_type = models.IntegerField(choices=TYPE_CHOICES)
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Modificado em', auto_now=True)
    request_accepted = models.ForeignKey(
        'Request', related_name='request_accepted', on_delete=models.CASCADE, blank=True, null=True)

    deleted = models.IntegerField(default=0)
    deleted_at = models.IntegerField(blank=True, null=True)

    class Meta:
        def __str__(self):
            return self.material.title


class Request(models.Model):
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Modificado em', auto_now=True)


class Complaint(models.Model):
    COMPLAINT_CHOICES = [
        (0, 'Conteúdo impróprio'),
        (1, 'Conteúdo não educacional'),
        (2, 'Outro')
    ]
    message = models.TextField(null=True, blank=True)
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    complaint_type = models.IntegerField(choices=COMPLAINT_CHOICES)

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="pt-br">

<head>
  <link rel="icon" href="{% static 'images/ICO.png' %}" />
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge" />
  <!--Materialize css-->
  <link rel="stylesheet" href="{% static 'css/materialize.css' %}" />
  <link rel="stylesheet" href="{% static 'css/app.css' %}" />
  <script src='https://api.mapbox.com/mapbox-gl-js/v1.0.0/mapbox-gl.js'></script>
  <link href='https://api.mapbox.com/mapbox-gl-js/v1.0.0/mapbox-gl.css' rel='stylesheet' />
  {% block head %} {% endblock %}
  <title>{% block title %} {% endblock %}</title>
</head>

<body>
  <main>
    <nav>
        
      <div class="nav-wrapper">
        {% if user.is_authenticated %}

        Olá, {{user.get_username}}!
        <a href="#" data-target="slide-out" class="sidenav-trigger show-on-large"><i class="material-icons">menu</i></a>
        {% endif %}

        <ul class="right hide-on-med-and-down">
          
          <!-- <li>
            <form id="navbarsearch">
              <div class="navfix">
                <div id="navfix2">
                  <div class="input-field">
                    <input id="search" type="search" placeholder="Buscando algo?"
                      onfocus="this.placeholder='Digite o nome da publicação...'"
                      onfocusout="this.placeholder='Buscando algo?'">
                  </div>
                </div>
              </div>
            </form>
          </li> -->
          <li>
            <a href="{% url 'home' %}"><img class="responsive-img left" style="width:180px; margin-left: 20px"
              src="{% static 'images/BRICADEMY.png' %}" /></a>
          </li>
          {% if not user.is_authenticated %}
          <li>
            <a href="{% url 'users:login' %}"><i class="material-icons right">account_circle </i>Entrar</a>
          </li>
          <li>
            <a href="{% url 'users:signup' %}"><i class="material-icons right">person_add</i>Criar Conta</a>
          </li>


          {% else %}
          <li>
            <a href="{% url 'users:logout' %}"><i class="material-icons right">exit_to_app</i>Sair</a>
          </li>
          {% endif %}
        </ul>

      </div>
    </nav>
    <ul class="sidenav" id="mobile-demo">
      {% if not user.is_authenticated %}
      <li>
        <a href="{% url 'users:login' %}"><i class="material-icons left">account_circle </i>Entrar</a>
      </li>
      <li>
        <a href="{% url 'users:signup' %}"><i class="material-icons left">person_add</i>Criar Conta</a>
      </li>
      {% else %}
      <li>
        <a href="{% url 'users:logout' %}"><i class="material-icons left">exit_to_app</i>Sair
        </a>
      </li>
      {% endif %}
    </ul>

    <div class="row">

      <div class="col s12 m12 l12">
        <ul id="slide-out" class="sidenav">
          <li>
            <div class="user-view">
              <div class="background">
                <img src="https://materializecss.com/images/office.jpg" />
              </div>
              <a href="#user"><img class="circle" src="{{user.profile.avatar.url}}" /></a>
              <a href="#name"><span class="white-text name">{{user.get_full_name}}</span></a>
              <a href="#email"><span class="white-text email">{{user.email}}</span></a>
            </div>
          </li>
          <li>
            <a href="{% url 'home' %}"><i class="material-icons left">home</i>Início</a>
          </li>
          <li>
            <a href="{% url 'users:perfil' %}"><i class="material-icons">person</i>Perfil</a>
          </li>
          <li>
            <a href="{% url 'materials:list_material' %}"><i class="material-icons">library_books</i>Materiais</a>
          </li>
          <!--<li>
            <a href="{% url 'materials:solicitacoes_recebidas' %}"><i
                class="material-icons">library_books</i>Solicitações recebidas</a>
          </li>-->
          <li>
            <a href="{% url 'ads:meus_anuncios' %}"><i
                class="material-icons">library_books</i>Meus anúncios</a>
          </li>
          <li>
            <a href="{% url 'materials:minhas_solicitacoes' %}"><i class="material-icons">library_books</i>Minhas
              solicitações</a>
          </li>
          <li>
            <div class="divider"></div>
          </li>
          <li><a class="subheader"></a>
          </li>
          <li><a class="waves-effect" href="{% url 'users:logout' %}"><i class="material-icons">exit_to_app</i>Sair</a>
          </li>
        </ul>

      </div>
      <div class="container">
        {% block content %} {% endblock %}
      </div>
  </main>

  <footer class="page-footer">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Sobre o Bricademy</h5>
          <p class="grey-text text-lighten-4">O Bricademy é uma aplicação web que permite aos usuários disponibilizarem
            materiais acadêmicos para venda, doação ou empréstimo...</p>
          <a href="{% url 'sobre' %}" class="waves-effect waves-light btn"><i class="material-icons right">add</i>Ver</a>    
        </div>
        <div class="col l4 offset-l2 s12">
          <h5 class="white-text">Criadores</h5>
          <ul>
            <li><a class="grey-text text-lighten-3" href="https://github.com/anaveroneze">Ana Veroneze</a></li>
            <li><a class="grey-text text-lighten-3" href="https://github.com/ClaitonDenardi">Claiton Denardi</a></li>
            <li><a class="grey-text text-lighten-3" href="https://github.com/doyleSM">Gabriel Doyle</a></li>
            <li><a class="grey-text text-lighten-3" href="https://github.com/jcamaral">Juliano Cesar Colling</a></li>
            <li><a class="grey-text text-lighten-3" href="https://github.com/odcmello">Otávio Mello</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
        Bricacademy © 2019 All Rights Reserved
      </div>
    </div>
  </footer>

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
  <!-- Jquery -->
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>

  <!--Materialize javascript-->
  <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>

  <!--Js da aplicação-->
  <script type="text/javascript" src="{% static 'js/app.js' %}"></script>

  {% for message in messages %}
  <script>
    M.toast({ html: "{{ message }}", classes: '{{message.tags}} rounded' })
  </script>
  {% endfor %}

  <script>
    document.addEventListener('DOMContentLoaded', function () {
      var elems = document.querySelectorAll('.sidenav');
      var instances = M.Sidenav.init(elems, options);
    });
  </script>

</body>

</html>

templates/home.html
{% extends 'base.html' %} {% load static %} 
{% block title %} Home {% endblock %} 
{% block content %}
{% block head %}
<script src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.3.0/mapbox-gl-geocoder.min.js"></script>
<link
  rel="stylesheet"
  href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.3.0/mapbox-gl-geocoder.css"
  type="text/css"
/>
{% endblock head %}

<style>
  .filter-ctrl {
    top: 10px;
    right: 10px;
    z-index: 1;
    width: 180px;
  }

  .filter-ctrl input[type="text"] {
    font: 20px "Helvetica Neue", Arial, Helvetica, sans-serif;
    width: 100%;
    border: 0;
    background-color: #c9c9c9;
    height: 40px;
    margin: 0;
    color: rgba(0, 0, 0, 0.5);
    padding: 10px;
    box-shadow: 0 0 0 2px rgba(0, 0, 0, 0.1);
    border-radius: 3px;
  }

  .card-title {
    text-transform: capitalize;
  }

  .card-image {
    height: 300px;
    overflow: hidden;
  }

  h2.ridge {
    border-style: ridge;
  }

  @media screen and (max-width: 992px) {
    div {
      width: 350px;
    }
  }
</style>

<center>
  <h2 style="color: #ee6e73; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;text-shadow: 2px 2px 3px #000;"><b>Materiais Disponíveis</b></h2>
</center>
<br />

<div class="row">
  <h4 class="center">Venda</h4>
  <hr />

  {% for material in materiais %} 

    {% if material.1 == 0 %}
    <div class="col m3">
      <div class="card large">
        <div class="card-image waves-effect waves-block waves-light">
          <img
            class="activator"
            src="static/images/{{ material.0.image }}"
            alt="img"
          />
        </div>
        <div class="card-content">
          <span class="card-title center">
            <p class="flow-text truncate">
              <b>{{ material.0.title }}</b>
            </p>
          </span>

          <center>
            <div class="card-action">
              <a
                href="{% url 'ads:vermais_url' material.0.pk %}"
                class="btn btn-primary"
                role="button"
                >Ver mais</a
              >
            </div>
          </center>
        </div>

        <div class="card-reveal">
          <span class="card-title grey-text text-darken-4"
            ><b></b><i class="material-icons right">close</i></span
          >
          <span class="card-title grey-text text-darken-4"
            ><b>{{ material.0.title }}</b></span
          >
          <hr />
          <p>
            <b>Autor:</b> {{ material.0.author }}<br />
            <b>ISBN:</b> {{ material.0.ISBN }}<br />
            <b>Editora:</b> {{ material.0.publishing_company }}<br />
            <b>Conservação:</b> {{ material.0.get_conservation_display }}<br />
            <b>Tipo:</b> {{ material.0.get_category_display }}<br />
            <b>Assuntos:</b> {% for subject in material.0.subject.all %}
            {{ subject }}, {% endfor %}
          </p>
        </div>
      </div>
    </div>
    {% endif %} {% endfor %}
</div>

<div class="row">
  <h4 class="center">Doação</h4>
  <hr />
  {% for material in materiais %} 
  {% if material.1 == 1 %}
  <div class="col m3">
    <div class="card large">
      <div class="card-image waves-effect waves-block waves-light">
        <img
          class="activator"
          src="static/images/{{ material.0.image }}"
          alt="img"
        />
      </div>
      <div class="card-content">
        <span class="card-title center">
          <p class="flow-text truncate">
            <b>{{ material.0.title }}</b>
          </p>
        </span>
        <center>
          <div class="card-action">
            <a
              href="{% url 'ads:vermais_url' material.0.pk %}"
              class="btn btn-primary"
              role="button"
              >Ver mais</a
            >
          </div>
        </center>
      </div>
      <div class="card-reveal">
        <span class="card-title grey-text text-darken-4"
          ><b></b><i class="material-icons right">close</i></span
        >
        <span class="card-title grey-text text-darken-4"
          ><b>{{ material.0.title }}</b></span
        >
        <hr />
        <p>
          <b>Autor:</b> {{ material.0.author }}<br />
          <b>ISBN:</b> {{ material.0.ISBN }}<br />
          <b>Editora:</b> {{ material.0.publishing_company }}<br />
          <b>Conservação:</b> {{ material.0.get_conservation_display }}<br />
          <b>Tipo:</b> {{ material.0.get_category_display }}<br />
          <b>Assuntos:</b> {% for subject in material.0.subject.all %}
          {{ subject }}, {% endfor %}
        </p>
      </div>
    </div>
  </div>
  {% endif %} {% endfor %}
</div>

<div class="row">
  <br />
  <h4 class="center">Empréstimo </h4>
  <hr />
  {% for material in materiais %} 
  {% if material.1 == 2 %}
  <div class="col m3">
    <div class="card large">
      <div class="card-image waves-effect waves-block waves-light">
        <img
          class="activator"
          src="static/images/{{ material.0.image }}"
          alt="img"
        />
      </div>
      <div class="card-content">
        <span class="card-title center">
          <p class="flow-text truncate">
            <b>{{ material.0.title }}</b>
          </p>
        </span>
        <center>
          <div class="card-action">
            <a
              href="{% url 'ads:vermais_url' material.0.pk %}"
              class="btn btn-primary"
              role="button"
              >Ver mais</a
            >
          </div>
        </center>
      </div>
      <div class="card-reveal">
        <span class="card-title grey-text text-darken-4"
          ><b></b><i class="material-icons right">close</i></span
        >
        <span class="card-title grey-text text-darken-4"
          ><b>{{ material.0.title }}</b></span
        >
        <hr />
        <p>
          <b>Autor:</b> {{ material.0.author }}<br />
          <b>ISBN:</b> {{ material.0.ISBN }}<br />
          <b>Editora:</b> {{ material.0.publishing_company }}<br />
          <b>Conservação:</b> {{ material.0.get_conservation_display }}<br />
          <b>Tipo:</b> {{ material.0.get_category_display }}<br />
          <b>Assuntos:</b> {% for subject in material.0.subject.all %}
          {{ subject }}, {% endfor %}
        </p>
      </div>
    </div>
  </div>
  {% endif %} {% endfor %}
</div>


<br />
<h4 class="center">VER NO MAPA</h4>


<div class="filter-ctrl">
  <input id="filter-input" type="text" name="filter" placeholder="Buscar por título" />
</div>
<div>Encontrados: <input readonly id="encontrados" /></div>
 
<div id="map" style="width: 100%; height:500px;"></div>

<script>
    navigator.geolocation.getCurrentPosition(function(position) {
      mapboxgl.accessToken = "{{ token }}";
      var MarkFilter = []; // Will contain a list used to filter against.
      var AllMarks = [];
      var label = document.getElementById("encontrados");
      var filterInput = document.getElementById('filter-input');
      var map = new mapboxgl.Map({
        container: "map", // Container ID
        style: "mapbox://styles/mapbox/navigation-guidance-day-v2",

        center: [position.coords.longitude, position.coords.latitude], // Starting position [lng, lat]
        zoom: 13 // Starting zoom level
      });


      map.addControl(new mapboxgl.GeolocateControl({
        positionOptions: {
        enableHighAccuracy: true
      },
        trackUserLocation: true
      }));

      var geojson = {
        id: "places",
        type: "FeatureCollection",
        features: [
        {% for anuncio in anuncios %}
        {
            type: "Feature",
            properties: {
              adType: {{anuncio.ad_type}},
              title: "{{anuncio.material.title}}",
              id: {{anuncio.pk}},
              idMat: {{anuncio.material.id}},
              tipoAnuncio: "{{anuncio.get_ad_type_display}}",
              iconSize: [20, 20],
              tipo: {{anuncio.material.category}},
            },
            geometry: {
              type: "Point",
              coordinates: [{{anuncio.longitude}}, {{anuncio.latitude}}],
            }
          },
          {% endfor %}
        ]
      };

      label.value = geojson.features.length;
      geojson.features.forEach(function(marker) {
      var el = document.createElement("div");
      el.className = "marker";
      el.style.backgroundImage = "url(http://localhost:8000/static/images/map/livro.svg)";

      el.style.width = marker.properties.iconSize[0] + "px";
      el.style.height = marker.properties.iconSize[1] + "px";
      marker.el = el;
      AllMarks.push(marker);
      // add marker to map
      new mapboxgl.Marker(el).setLngLat(marker.geometry.coordinates).setPopup(new mapboxgl.Popup({ offset: 25 }) // add popups
      .setHTML('<b>Título</b>: ' + marker.properties.title + '<p><b>Tipo: </b>'+ marker.properties.tipoAnuncio +  '</p><p><a href=\"/ads/vermais/'+marker.properties.idMat +"\">" + "<span class='badge red white-text'>Ver mais</span>" + '</a></p>')).addTo(map);});      // Create a popup, but don't add it to the map yet.

      var popup = new mapboxgl.Popup({
        closeButton: false,
        closeOnClick: false
      });

      map.on("load", "places", function(e) {
        // Change the cursor style as a UI indicator.
        map.getCanvas().style.cursor = "pointer";

        var coordinates = e.features[0].geometry.coordinates.slice();
        var description = e.features[0].properties.description;

        // Ensure that if the map is zoomed out such that multiple
        // copies of the feature are visible, the popup appears
        // over the copy being pointed to.
        while (Math.abs(e.lngLat.lng - coordinates[0]) > 180) {
          coordinates[0] += e.lngLat.lng > coordinates[0] ? 360 : -360;
        }

        // Populate the popup and set its coordinates
        // based on the feature found.
        popup
          .setLngLat(coordinates)
          .setHTML(description)
          .addTo(map);
      });

      filterInput.addEventListener('keyup', function(e) {
      var value = e.target.value.trim();
      geojson.features.forEach(function(marker) {
        if(!(marker.properties.title.indexOf(value) !== -1)){
          //MarkFilter.push(marker);
          //se a marca nao tiver nada com o texto digitado remove

          var removeIndex = AllMarks.indexOf(marker);
          if(removeIndex > -1){
            AllMarks.splice(removeIndex, 1);
            marker.el.remove();
          }

        }else{
          if(!(AllMarks.includes(marker))){
           var el = document.createElement("div");
           el.className = "marker";
           el.style.backgroundImage = "url(http://localhost:8000/static/images/map/livro.svg)";

           el.style.width = marker.properties.iconSize[0] + "px";
           el.style.height = marker.properties.iconSize[1] + "px";

           marker.el = new mapboxgl.Marker(el).setLngLat(marker.geometry.coordinates).setPopup(new mapboxgl.Popup({ offset: 25 }) // add popups
         .setHTML('<b>Título</b>: ' + marker.properties.title + '<p><b>Tipo: </b>'+ marker.properties.tipoAnuncio +  '</p><p><a href=\"/ads/vermais/'+marker.properties.idMat +"\">" + "<span class='badge red white-text'>Ver mais</span>" + '</a></p>'));
           marker.el.addTo(map);
           AllMarks.push(marker);
         }
        }
      });
      label.value = AllMarks.length;

  });
  });
</script>

{% endblock %}

templates/sobre.html
{% extends 'base.html' %} 
{% load static %} 
{% block title %} Sobre {% endblock %} 

{% block content %}

<center><h3 style="color: #ee6e73; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;text-shadow: 2px 2px 3px #000;">Sobre</h3></center>
<br>

<p>
O Bricademy é uma aplicação web que permite aos usuários
disponibilizarem a mídia física de materiais acadêmicos para venda, doação ou
empréstimo, e permite usuários cadastrados no sistema solicitarem os mesmos. O
sistema conta com um acervo composto pelos anúncios dos usuários que poderá ser
explorado por qualquer usuário. Dessa forma a realização de trocas e vendas de
publicações pode ser feita de maneira rápida e segura entre pessoa de diversas
regiões do país, através de uma interface simples e intuitiva. 
</p>
<br>
<br>
<br>
{% endblock %}