ads/urls.py
from django.urls import path
from .views import index, solicitacao, vermais, negociacao, excluir_anuncio, cria_anuncio, meusanuncios, solicitacoesanuncio, aceitar, denuncia
app_name = 'ads'
urlpatterns = [
    path('', index, name="index_url"),
    path('novo/<int:pk>/<int:tipo>', cria_anuncio, name="ad_url"),
    path('excluir/<int:pk>', excluir_anuncio, name="excluir_url"),
    path('vermais/<int:pk>', vermais, name="vermais_url"),
    path('solicitacao/<int:anuncio>/<int:pk>',
         solicitacao, name="solicitacao_url"),
    path('negociacao/<int:pk>', negociacao, name="negociacao_url"),
    path('anuncios/', meusanuncios, name="meus_anuncios"),
    path('solicitacoes/<int:pk>', solicitacoesanuncio,
         name='solicitacoes_anuncio'),
    path('aceitar/<int:ad_pk>/<int:req_pk>', aceitar, name="aceitar"),
    path('denuncia/<int:pk>', denuncia, name="denuncia")
]

bricademy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import home, homemap, sobre
from users import urls as users_urls
from materials import urls as materials_urls
from ads import urls as ads_urls
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('', home, name="home"),
    path('map/', homemap, name="map"),
    path('sobre/', sobre, name="sobre"),
    path('materials/', include(materials_urls)),
    path('users/', include(users_urls)),
    path('ads/', include(ads_urls)),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

users/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from .views import signup
from .views import logout_user, Login, profile, newAddress, update_profile

app_name = 'users'
urlpatterns = [
    path('perfil', profile, name="perfil"),
    path('cadastro', signup, name="signup"),
    path('editar', update_profile, name="update_url"),
    path('login', Login.as_view(), name='login'),
    path('logout', logout_user, name='logout'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html',
                                                                 email_template_name='registration/password_reset_email.html',
                                                                 subject_template_name='registration/password_reset_subject.txt',
                                                                 success_url=reverse_lazy(
                                                                     'users:password_reset_done')
                                                                 ), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html',
                                                                                                 success_url=reverse_lazy('users:password_reset_complete')), name='password_reset_confirm'),
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    path('endereco', newAddress, name='new_address'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
from materials.models import Subject


class Profile(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, primary_key=True)
    birth = models.DateField(null=True, blank=True)
    CPF = models.CharField('CPF', max_length=15, default="N/A")
    interest = models.ManyToManyField(Subject)
    avatar = models.ImageField(
        'avatar', upload_to='users', default='/users/avatar.png', blank=True, null=True)

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()


class Address(models.Model):
    CEP = models.CharField('CEP', max_length=15)
    city = models.CharField('Cidade', max_length=50)
    district = models.CharField('Bairro', max_length=30)
    street = models.CharField('Rua', max_length=140)
    number = models.CharField('Numero', max_length=8)
    complement = models.CharField('Complemento', max_length=100)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.street + ', ' + self.number + ', ' + self.district + ' - ' + self.city


class Evaluation(models.Model):
    ANALYZES_CHOICES = [
        (0, 'Material bem conservado'),
        (1, 'Responde rápido'),
        (2, 'Simpático')
    ]
    rate = models.IntegerField()
    comment = models.TextField()
    evaluator = models.ForeignKey(
        User, related_name='evaluator', on_delete=models.CASCADE, blank=True, null=True)
    evaluated = models.ForeignKey(
        User, related_name='evaluated', on_delete=models.CASCADE, blank=True, null=True)
    analize = models.IntegerField(
        choices=ANALYZES_CHOICES, blank=True, null=True)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Address


class ProfileForm(UserCreationForm):
    birth = forms.DateField(
        required=False, help_text='Formato: YYYY-MM-DD')
    CPF = forms.CharField(required=False)
    avatar = forms.ImageField()

    class Meta:
        model = User
        fields = ('avatar', 'first_name', 'last_name', 'username', 'email', 'birth',
                  'CPF', 'password1', 'password2')


class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ['street', 'number', 'complement',
                  'district', 'city', 'CEP', ]

users/views.py
from .forms import AddressForm
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView
from django.contrib.auth import update_session_auth_hash
from .forms import ProfileForm, AddressForm
from .models import Address
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.contrib.auth.decorators import login_required


# Create your views here.
def signup(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()  # load the profile instance created by the signal
            user.profile.birth = form.cleaned_data.get(
                'birth')
            user.profile.CPF = form.cleaned_data.get('CPF')
            user.profile.avatar = form.cleaned_data.get('avatar')
            user.save()

            return redirect('users:login')
        else:
            # error
            pass
    else:
        form = ProfileForm()
    return render(request, 'registration/signup.html', {'form': form})


@login_required
def update_profile(request):
    if request.method == 'POST':
        profile_form = ProfileForm(request.POST, request.FILES)
        if profile_form.is_valid():
            username = request.POST['username']
            password = request.POST['password1']
            profile_form.save()
            #update_session_auth_hash(request, profile_form.user)
            user = authenticate(request, username=username,
                                password=password)

            if user is not None:
                user.profile.birth = profile_form.cleaned_data.get(
                    'birth')
                user.profile.CPF = profile_form.cleaned_data.get('CPF')
                user.profile.avatar = profile_form.cleaned_data.get('avatar')
                user.save()
                login(request, user)
                messages.success(request, 'Dados atualizados com sucesso!!')
            else:
                messages.error(request, 'Falha ao atualizar os dados')

            return render(request, 'users/profile.html', {})
        else:
            messages.error(request, 'Falha ao atualizar os dados')
    else:
        profile_form = ProfileForm(instance=request.user)
    return render(request, 'users/edit_profile.html', {'profile_form': profile_form})


class Login(LoginView):
    form_class = AuthenticationForm
    authentication_form = None
    template_name = 'registration/login.html'
    redirect_authenticated_user = 'home'


@login_required
def logout_user(request):
    logout(request)
    return redirect('home')


@login_required
def profile(request):
    address = Address.objects.filter(user=request.user).first()
    return render(request, 'users/profile.html',  {'address': address})


@login_required
def newAddress(request):
    if request.method == 'POST':
        form = AddressForm(request.POST)
        if form.is_valid():
            old_address = Address.objects.filter(user=request.user)
            if(old_address):
                old_address.delete()
            form.instance.user = request.user
            form.save()
            messages.success(request, 'Endereço salvo com sucesso!')

            return redirect('users:perfil')
        else:
            messages.error(request, 'Falha ao salvar endereço')
            return redirect('users:perfil')
    else:
        try:
            old_address = Address.objects.get(user=request.user)
            form = AddressForm(instance=old_address)
        except:
            form = AddressForm()
        return render(request, 'users/new_address.html', {'form': form})

templates/users/edit_profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Editar perfil
{% endblock %}

{% block content %}


    <div class="card-panel">
      <h4 class="header2 txtavatar">Editar perfil</h4>
      <div class="row">
        <form class="col s12" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="row">
            <div class="">
              <label for="id_avatar">
                <img
                  class="imgcenter"
                  src="{% static '/images/users/avatar.png' %}"
                  width="150"
                  height="150"
                />
              </label>
              <p class="txtavatar">clique na imagem para escolher seu avatar</p>
              <input
                style="display: none;"
                type="file"
                name="avatar"
                accept="image/*"
                required
                id="id_avatar"
              />
            </div>
          </div>
          <div class="row">
            <form class="col s12">
              <div class="row">
                <div class="input-field col s12">
                  <input
                    type="text"
                    name="first_name"
                    maxlength="30"
                    id="id_first_name"
                  />
                  <label for="id_first_name">Primeiro Nome:</label>
                </div>
              </div>
              <div class="row">
                <div class="input-field col s12">
                  <input
                    type="text"
                    name="last_name"
                    maxlength="150"
                    id="id_last_name"
                  />
                  <label for="id_last_name">Último nome:</label>
                </div>
              </div>
              <div class="row">
                <div class="input-field col s12">
                  <input
                    type="text"
                    name="username"
                    maxlength="150"
                    required
                    autofocus
                    id="id_username"
                  />
                  <label for="id_username">Usuário:</label>
                </div>
              </div>
              <div class="row">
                <div class="input-field col s12">
                  <input
                    type="email"
                    name="email"
                    maxlength="254"
                    id="id_email"
                  />
                  <label for="id_email">E-mail:</label>
                </div>
              </div>
              <div class="row">
                <div class="input-field col s12">
                  <input
                    type="password"
                    name="password1"
                    required
                    id="id_password1"
                  />
                  <label for="id_password1">Senha</label>
                </div>
              </div>

              <div class="row">
                <div class="input-field col s12">
                  <input
                    type="password"
                    name="password2"
                    required
                    id="id_password2"
                  />
                  <label for="id_password2">Confirmação de senha:</label>
                </div>
              </div>

              <button class="btn" type="submit">Salvar</button>
            </form>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
  var avatarInput = document.getElementById("id_avatar");
  var img = document.querySelector("label[for=id_avatar] img");
  avatarInput.onchange = function(e) {
    img.classList.add("preview");
    img.src = URL.createObjectURL(e.target.files[0]);
  };
</script>

{% endblock %}

templates/users/new_address.html
{% extends 'base.html' %} 
{% block title %}
Endereço
{% endblock %}
{% load static %} {% block content %}
<div class="card-panel">
  <h4 class="header2 txtavatar">Endereço</h4>
  <div class="row">
    <form class="col s12" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button class="btn" type="submit">Salvar</button>
    </form>
  </div>
</div>

{% endblock %}

templates/users/profile.html
{% extends 'base.html' %} {% load static %} 
{% block title %}
Perfil
{% endblock %}
{% block content %}

<div class="row">
  <br /><br /><br /><br />
  <div class="col m6">
    <div id="profile-card" class="card">
      <div class="card-image waves-effect waves-block waves-light">
        <img
          class="activator"
          src="https://materializecss.com/images/office.jpg"
          alt="user bg"
        />
      </div>
      <div class="card-content">
        <img
          src="{{ request.user.profile.avatar.url }}"
          height="100"
          width="100"
          alt=""
          class="circle responsive-img activator card-profile-image cyan lighten-1 padding-2"
        />
        <a
          href="{% url 'users:update_url' %}"
          class="btn-floating btn-move-up waves-effect waves-light red accent-2 z-depth-4 right"
          ><i class="material-icons">edit</i></a
        >
        <span class="card-title activator grey-text text-darken-4"
          >{{ user.first_name }} {{ user.last_name }}</span
        >
        <p><i class="material-icons">perm_identity</i> {{ user.username }}</p>
        <p><i class="material-icons">email</i> {{ user.email }}</p>
      </div>
      <div class="card-reveal">
        <span class="card-title grey-text text-darken-4"
          >{{ user.first_name }} {{ user.last_name }}
          <i class="material-icons right">close</i>
        </span>
        <p><i class="material-icons">perm_identity</i> {{ user.username }}</p>
        <p><i class="material-icons">email</i> {{ user.email }}</p>
        <p><i class="material-icons">cake</i> {{ user.profile.birth }}</p>
        <p><i class="material-icons">fingerprint</i> {{ user.profile.CPF }}</p>
        <p></p>
        <p></p>
      </div>
    </div>
  </div>
  <div class="col m6">
    <div id="profile-card" class="card">
      <div class="card-image waves-effect waves-block waves-light">
        <img
          class="activator"
          src="https://cdn.mapsinternational.co.uk/pub/media/catalog/product/cache/afad95d7734d2fa6d0a8ba78597182b7/b/l/blue-world-map-wallpaper_wp00823_1.jpg"
          alt="user bg"
        />
      </div>
      <div class="card-content">
        <a
          href="{% url 'users:new_address' %}"
          class="btn-floating btn-move-up waves-effect waves-light red accent-2 z-depth-4 right"
          ><i class="material-icons">edit</i></a
        >
        <span class="card-title activator grey-text text-darken-4"
          >Endereço</span
        >
        <p>
          <i class="material-icons activator">location_on</i>
          {{ address.street }} {{ address.number }}
        </p>
        <p>
          <i class="material-icons activator">location_city</i>
          {{ address.city }}
        </p>
      </div>
      <div class="card-reveal">
        <span class="card-title grey-text text-darken-4"
          >Endereço
          <i class="material-icons right">close</i>
        </span>
        <p>Rua: {{ address.street }}</p>
        <p>Número: {{ address.number }}</p>
        <p>Complemento: {{ address.complement }}</p>
        <p>Bairro: {{ address.district }}</p>
        <p>Cidade: {{ address.city }}</p>
        <p>CEP: {{ address.CEP }}</p>
      </div>
    </div>
  </div>
</div>

{% endblock %}